---
date: "2017-04-14"
title: "Using R and lmer to fit different longitudinal models"
output:
  html_document:
    toc: true
    toc_float: true
    numbe\epsilon_sections: FALSE
author: "Hicham Zmarrou"
---

## Introduction

In this guide we have compiled some of the more common and/or useful models, and how to fit them using `lme4::lmer()`. The tutorial will cover the common two-level random intercept-slope model, and three-level models when subjects are clustered due to some higher level grouping (such as therapists), partially nested models were there are clustering in one group but not the other, and different level 1 residual covariances (such as AR(1)). The goal of this tutorial is to show how to fit these longitudinal models in `R`, not to cover the statistical theory behind them, or how to interpret them.

## Data format

In all examples we assume this data structure.

```{r}
suppressWarnings(suppressMessages(library(tidyverse)))

mydata <- tribble(
  ~subjects, ~X, ~therapist,~time,~y,
  #--|--|----
  1,0,1,0,10,
  1,0,1,1,12,
  1,0,1,2,14,
  2,0,1,0,4,
  2,0,1,1,14,
  2,0,1,2,13,
  3,0,2,0,12,
  3,0,2,1,15,
  3,0,2,2,16,
  4,0,2,0,17,
  4,0,2,1,13,
  4,0,2,2,12,
  5,0,3,0,15,
  5,0,3,1,13,
  "...","...","...","...","..."
)
knitr::kable(mydata)

```

Where `subjects` is each subject's id, `X` represent treatment allocation and is coded 0 or 1, `therapist` is the refers to either clustering due to therapists, or for instance a participant's group in group therapies. `Y` is the outcome variable.

## Longitudinal two-level model

We will begin with the two-level model, where we have repeated measures on individuals in different treatment groups.

### Unconditional model

Model formulation

$$
\begin{align}
\text{Level 1}& \notag\\\
Y_{ij} &= \beta_{0j}  + \epsilon_{ij}\\\
\text{Level 2}& \notag\\\
\beta_{0j} &= \gamma_{00} + U_{0j} 
\end{align}
$$

with,

$$
\begin{equation}
U_{0j} \sim\mathcal{N}(0, ~\sigma_{00}^2)
,
\end{equation}
$$

and 
$$
\begin{equation}
\epsilon_{ij} \sim\mathcal{N}(0, ~\sigma^2)
\end{equation}
$$

To fit this model we run

```
# lme4
lmer(y ~ 1 + (1 | subjects), data=mydata)

```

### Unconditional growth model
Model formulation
$$
\begin{align}
\text{Level 1}& \notag\\\
Y_{ij} &= \beta_{0j} + \beta_{1j}t_{ij} + \epsilon_{ij}\\\
\text{Level 2}& \notag\\\
\beta_{0j} &= \gamma_{00} + U_{0j} \\\
\beta_{1j} &= \gamma_{10} + U_{1j} \\\
\end{align}
$$

with,

$$
\begin{equation}
\begin{pmatrix}
U_{0j} \\\
 U_{1j}
\end{pmatrix}
\sim\mathcal{N}
\left(
\begin{matrix}
0 &\\\
0
\end{matrix}
,
\begin{matrix}
 \sigma_{00}^2 & \sigma_{01}\\\
 \sigma_{01} & \sigma_{10}^2
\end{matrix}
\right)
,
\end{equation}
$$
and, 

$$
\begin{equation}
\epsilon_{ij} \sim\mathcal{N}(0, ~\sigma^2)
\end{equation}
$$

To fit this model we run

```
# lme4
lmer(y ~ time + (time | subjects), data=mydata)
```
### Conditional growth model

Model formulation
$$
\begin{align}
\text{Level 1}& \notag\\\
Y_{ij} &= \beta_{0j} + \beta_{1j}t_{ij} + \epsilon_{ij}\\\
\text{Level 2}& \notag\\\
\beta_{0j} &= \gamma_{00} + \gamma_{01} TX_j + U_{0j} \\\
\beta_{1j} &= \gamma_{10} + \gamma_{11} TX_j + U_{1j} \\\
\end{align}
$$

with,

$$
\begin{equation}
\begin{pmatrix}
U_{0j} \\\
 U_{1j}
\end{pmatrix}
\sim\mathcal{N}
\left(
\begin{matrix}
0 &\\\
0
\end{matrix}
,
\begin{matrix}
 \sigma_{00}^2 & \sigma_{01}\\\
 \sigma_{01} & \sigma_{10}^2
\end{matrix}
\right)
,
\end{equation}
$$

and, 

$$
\begin{equation}
\epsilon_{ij} \sim\mathcal{N}(0, ~\sigma^2)
\end{equation}
$$
To fit this model we run
```
# lme4
lmer(y ~ time * tx + (time | subjects), data=mydata)
```
### Conditional growth model: dropping random slope

Model formulation

$$
\begin{align}
\text{Level 1}& \notag\\\
Y_{ij} &= \beta_{0j} + \beta_{1j}t_{ij} + \epsilon_{ij}\\\
\text{Level 2}& \notag\\\
\beta_{0j} &= \gamma_{00} + \gamma_{01} TX_j + U_{0j} \\\
\beta_{1j} &= \gamma_{10} + \gamma_{11} TX_j \\\
\end{align}
$$

with 

$$
\begin{equation}
U_{0j} \sim\mathcal{N}(0, ~\sigma_{00}^2)
\end{equation}
$$

and,

$$
\begin{equation}
R_{ij} \sim\mathcal{N}(0, ~\sigma^2)
\end{equation}
$$

To fit this model we run

```
# lme4
lmer(y ~ time * tx + (1 | subjects), data=mydata)
```
### Conditional growth model: dropping random intercept
Model formulation

$$
\begin{align}
\text{Level 1}& \notag\\\
Y_{ij} &= \beta_{0j} + \beta_{1j}t + \epsilon_{ij}\\\
\text{Level 2}& \notag\\\
\beta_{0j} &= \gamma_{00} + \gamma_{01} TX_j \\\
\beta_{1j} &= \gamma_{10} + \gamma_{11} TX_j + U_{1j}\\\
\end{align}
$$

with 

$$
\begin{equation}
\epsilon_{ij} \sim\mathcal{N}(0, ~\sigma^2)
\end{equation}
$$

and 

$$
\begin{equation}
R_{ij} \sim\mathcal{N}(0, ~\sigma^2)
\end{equation}
$$


To fit this model we run

```
# lme4
lmer(y ~ time * tx + ( 0 + time | subjects), data=mydata)
```

### Conditional growth model: dropping intercept-slope covariance
Model formulation

$$
\begin{align}
\text{Level 1}& \notag\\\
Y_{ij} &= \beta_{0j} + \beta_{1j}t + \epsilon_{ij}\\\
\text{Level 2}& \notag\\\
\beta_{0j} &= \gamma_{00} + \gamma_{01} TX_j + U_{0j} \\\
\beta_{1j} &= \gamma_{10} + \gamma_{11} TX_j + U_{1j} \\\
\end{align}
$$

with, 

$$
\begin{equation}
\begin{pmatrix}
U_{0j} \\\
 U_{1j}
\end{pmatrix}
\sim\mathcal{N}
\left(
\begin{matrix}
0 &\\\
0
\end{matrix}
,
\begin{matrix}
 \sigma_{00}^2 & 0\\\
 0 & \sigma_{10}^2
\end{matrix}
\right)
,
\end{equation}
$$

and, 

$$
\begin{equation}
\epsilon_{ij} \sim\mathcal{N}(0, ~\sigma^2)
\end{equation}
$$

to fit this model 

```
# lme4
lmer(y ~ time * tx + (time || subjects) , data=mydata)

# same as above            
lmer(y ~ time * tx + (1 | subjects) + (0 + time | subjects) , data=mydata)

```

## Three-level models

This part covers some different three-level models. In this examples clustering at the highest level is due to therapists. But the examples generalize to other forms of clustering as well, such as group therapy or clustering due to health-care provider.

## Conditional three-level growth model

model formulation:

$$
\begin{align}
\text{Level 1}& \notag\\\
Y_{ijk} &= \beta_{0jk} + \beta_{1jk}t_{ijk} + \epsilon_{ijk}\\\
\text{Level 2}& \notag\\\
\beta_{0jk} &= \gamma_{00k} + U_{0jk} \\\
\beta_{1jk} &= \gamma_{10k} + U_{1jk} \\\
\text{Level 3}& \notag\\\
\gamma_{00k} &= \delta_{000} + \delta_{001} TX_k + V_{0k} \\\
\gamma_{10k} &= \delta_{100} + \delta_{101} TX_k + V_{1k} \\\
\end{align}
$$

with, 

$$
\begin{equation}
\begin{pmatrix}
U_{0j} \\\
 U_{1j}
\end{pmatrix}
\sim\mathcal{N}
\left(
\begin{matrix}
0 &\\\
0
\end{matrix}
,
\begin{matrix}
 \sigma_{00}^2 & \sigma_{01}\\\
 \sigma_{01} & \sigma_{10}^2
\end{matrix}
\right)
,
\end{equation}
$$

and,

$$
\begin{equation}
\begin{pmatrix}
V_{0k} \\\
 V_{1k} \\\
\end{pmatrix}
\sim\mathcal{N}
\left(
\begin{matrix}
0 &\\\
0
\end{matrix}
,
\begin{matrix}
 \varphi_{00}^2 & \varphi_{01} \\\
 \varphi_{01} & \varphi_{10}^2 
\end{matrix}
\right)
,
\end{equation}
$$

and, 

$$
\begin{equation}
\epsilon_{ijk} \sim\mathcal{N}(0, ~\sigma^2)
\end{equation}
$$

To fit this model we use `therapist/subjects`, which specifies nesting. This formula expands to a main effect of therapist and a interaction between therapist and subjects (which is the subject level effect).

```
# lme
lmer(y ~ time * tx + (time | therapist/subjects), data=mydata)
## expands to
lmer(y ~ time * tx + (time | therapist:subjects) + (time | therapist), data=mydata)
```



